name: rw_help
description: Help plugin for RealWear HMT-1(Z1)
version: 1.0.0
homepage: https://github.com/Skyggedans/rw_help

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.rockwellits.rw_plugins.rw_help
    pluginClass: RwHelpPlugin
